In [38]:
#importing all the essential libraries


import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
%matplotlib inline

loading dataset


In [39]:
columns = ['sepal length','sepal width','petal length','petal width','class_lables']
# load the data
df = pd.read_csv('irisdataset.txt', names=columns)
df.head()

sepal length  sepal width  petal length  petal width class_lables
0           5.1          3.5           1.4          0.2       setosa
1           4.9          3.0           1.4          0.2       setosa
2           4.7          3.2           1.3          0.2       setosa
3           4.6          3.1           1.5          0.2       setosa
4           5.0          3.6           1.4          0.2       setosa

visualization of dataset

In [40]:
df.describe()

sepal length  sepal width  petal length  petal width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [41]:
#visualize the whole dataset
sns.pairplot(df,hue='class_lables')

seperating input columns and output columns


In [42]:
#seperate features and target
data=df.values

X=data[:,0:4]
Y=data[:,4]
print(X)
print(Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

SPLITTING THE DATA INTO TRAINING AND TESTING

In [43]:
#split the data to train and test dataset.
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)
print(y_train)

['versicolor' 'setosa' 'versicolor' 'versicolor' 'virginica' 'versicolor'
 'setosa' 'virginica' 'setosa' 'setosa' 'versicolor' 'virginica' 'setosa'
 'virginica' 'versicolor' 'virginica' 'virginica' 'versicolor' 'virginica'
 'versicolor' 'virginica' 'setosa' 'versicolor' 'versicolor' 'virginica'
 'virginica' 'virginica' 'setosa' 'virginica' 'versicolor' 'virginica'
 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa' 'versicolor'
 'versicolor' 'versicolor' 'setosa' 'setosa' 'versicolor' 'versicolor'
 'versicolor' 'setosa' 'setosa' 'setosa' 'virginica' 'setosa' 'virginica'
 'versicolor' 'virginica' 'virginica' 'virginica' 'virginica' 'virginica'
 'versicolor' 'setosa' 'versicolor' 'setosa' 'setosa' 'versicolor'
 'setosa' 'virginica' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'virginica' 'versicolor' 'virginica' 'virginica' 'virginica' 'virginica'
 'versicolor' 'setosa' 'setosa' 'setosa' 'versicolor' 'setosa'
 'versicolor' 'setosa' 'setosa' 'setosa' 'virginica' 'versicolor'
 

MODEL1:support vector machine algorithm

In [44]:
#support vector machine algorithm
from sklearn.svm import SVC

model_svc=SVC()
model_svc.fit(X_train,y_train)


SVC()

In [45]:
prediction1=model_svc.predict(X_test)
#calculate the accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,prediction1)*100)
for i in range(len(prediction1)):
  print(y_test[i],prediction1[i])

93.33333333333333
virginica virginica
setosa setosa
versicolor virginica
virginica virginica
setosa setosa
setosa setosa
virginica virginica
setosa setosa
setosa setosa
setosa setosa
virginica virginica
versicolor virginica
virginica virginica
setosa setosa
versicolor versicolor
virginica virginica
virginica virginica
setosa setosa
setosa setosa
versicolor versicolor
setosa setosa
virginica virginica
virginica virginica
versicolor versicolor
versicolor versicolor
setosa setosa
versicolor versicolor
setosa setosa
virginica virginica
versicolor versicolor


MODEL2:LOGISTIC REGRESSION

In [46]:
#LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
model_LR=LogisticRegression()
model_LR.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [47]:
prediction2=model_LR.predict(X_test)
#calculate the accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,prediction2)*100)
for i in range(len(prediction1)):
  print(y_test[i],prediction1[i])


93.33333333333333
virginica virginica
setosa setosa
versicolor virginica
virginica virginica
setosa setosa
setosa setosa
virginica virginica
setosa setosa
setosa setosa
setosa setosa
virginica virginica
versicolor virginica
virginica virginica
setosa setosa
versicolor versicolor
virginica virginica
virginica virginica
setosa setosa
setosa setosa
versicolor versicolor
setosa setosa
virginica virginica
virginica virginica
versicolor versicolor
versicolor versicolor
setosa setosa
versicolor versicolor
setosa setosa
virginica virginica
versicolor versicolor


MODEL3:DECISION TREE CLASSIFIER

In [48]:
#decision tree classifier
from sklearn.tree import DecisionTreeClassifier
model_DTC=DecisionTreeClassifier()
model_DTC.fit(X_train,y_train)

DecisionTreeClassifier()

In [49]:
prediction3=model_svc.predict(X_test)
#calculate the accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,prediction3))

0.9333333333333333


In [50]:
#A detailed classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,prediction2))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       1.00      0.75      0.86         8
   virginica       0.83      1.00      0.91        10

    accuracy                           0.93        30
   macro avg       0.94      0.92      0.92        30
weighted avg       0.94      0.93      0.93        30



In [51]:
X_new=np.array([[3,2,1,0.2],[4.9,2.2,3.8,1.1],[5.3,2.5,4.6,1.9]])
#prediction of the species from the input vector
prediction=model_svc.predict(X_new)
print("prediction of species: {}".format(prediction))

prediction of species: ['setosa' 'versicolor' 'virginica']
